# Generated by Django 5.2.6 on 2026-05-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_delete_dailymission_playerprofile_last_daily_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.subject')),
            ],
        ),
    ]
