# Generated by Django 5.2.6 on 2026-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_badge_dailymission_playerprofile_last_played_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyMission',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_daily_reward',
            field=models.DateField(blank=True, null=True),
        ),
    ]
