# Generated by Django 5.2.6 on 2026-05-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_question_difficulty_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RenameField(
            model_name='battleresult',
            old_name='total_questions',
            new_name='earned_coin',
        ),
        migrations.RenameField(
            model_name='battleresult',
            old_name='player',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='earned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='battleresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_daily_reward',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_played',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='battleresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battleresult',
            name='earned_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='rank',
            field=models.CharField(default='Bronze', max_length=30),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='total_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='coin_reward',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='question',
            name='xp_reward',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='📘', max_length=20),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='icon',
            field=models.CharField(default='🏅', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbadge',
            name='title',
            field=models.CharField(default='İlk Uğur', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='coin',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
