# Generated by Django 5.2.6 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_shopitem_usershopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wronganswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
