# Generated by Django 5.2.6 on 2026-05-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_wronganswer_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('frame', 'Avatar Frame'), ('badge', 'Badge'), ('glow', 'Glow Effect')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIQuizRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('difficulty', models.CharField(default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.subject')),
            ],
        ),
    ]
